title: XhuOffice

description: Welcome to XhuOffice Website!
show_excerpts: false 

minima:
  date_format: "%Y - %m - %d"

header_pages:
 - README.md
 - Services/root.md
 - OpenSource/root.md

remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag