title: XhuOffice

author:
  name: XhuOffice
  email: xhuoffice@xhuoffice.tk
description: Welcome to XhuOffice Website!
show_excerpts: false 

minima:
  date_format: "%Y - %m - %d"

header_pages:
 - README.md
 - Services/root.md
 - OpenSource/root.md
 - Notes/root.md

remote_theme: XhuOffice/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
